apiVersion: v1
name: istio-cni
version: 1.3.5
appVersion: 1.3.5
tillerVersion: ">=2.7.2"
description: Helm chart for istio-cni components
keywords:
  - istio-cni
  - istio
sources:
  - http://github.com/istio/cni
engine: gotpl
icon: https://istio.io/favicons/android-192x192.png
