# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: us-central1-docker.pkg.dev/google-samples/microservices-demo/adservice
  newTag: CONTAINER_IMAGES_TAG
- name: us-central1-docker.pkg.dev/google-samples/microservices-demo/cartservice
  newTag: CONTAINER_IMAGES_TAG
- name: us-central1-docker.pkg.dev/google-samples/microservices-demo/checkoutservice
  newTag: CONTAINER_IMAGES_TAG
- name: us-central1-docker.pkg.dev/google-samples/microservices-demo/currencyservice
  newTag: CONTAINER_IMAGES_TAG
- name: us-central1-docker.pkg.dev/google-samples/microservices-demo/emailservice
  newTag: CONTAINER_IMAGES_TAG
- name: us-central1-docker.pkg.dev/google-samples/microservices-demo/frontend
  newTag: CONTAINER_IMAGES_TAG
- name: us-central1-docker.pkg.dev/google-samples/microservices-demo/loadgenerator
  newTag: CONTAINER_IMAGES_TAG
- name: us-central1-docker.pkg.dev/google-samples/microservices-demo/paymentservice
  newTag: CONTAINER_IMAGES_TAG
- name: us-central1-docker.pkg.dev/google-samples/microservices-demo/productcatalogservice
  newTag: CONTAINER_IMAGES_TAG
- name: us-central1-docker.pkg.dev/google-samples/microservices-demo/recommendationservice
  newTag: CONTAINER_IMAGES_TAG
- name: us-central1-docker.pkg.dev/google-samples/microservices-demo/shippingservice
  newTag: CONTAINER_IMAGES_TAG
