apiVersion: v1
kind: ConfigMap
metadata:
  name: multicloud-config
  namespace: default
data:
  AWS_ACCOUNTING_URL: "http://54.163.148.73:8080"
  AZURE_ANALYTICS_URL: "http://20.160.153.10:8080"
  GCP_CRM_URL: "http://10.2.0.2:8080"
  GCP_INVENTORY_URL: "http://10.132.0.3:8080"
---
# Apply this ConfigMap first, then update your loadgenerator deployment to use it
# kubectl apply -f multicloud-config.yaml 
